name: Test

on: [push, pull_request]

jobs:
  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build with Maven
        run: python3 -m unittest discover -v
        working-directory: python
