name: Test

on: [push, pull_request]

jobs:
  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install requirements
        run: python3 -m pip install --no-cache-dir -r requirements.txt -r linux-requirements.txt --user
        working-directory: python

      - name: Run unittest
        run: python3 -m unittest discover -v
        working-directory: python
